site_name: Oh My Graphs!
copyright: Copyright &copy; 2024 - present Oh My Graphs!

theme:
  name: material
  logo: assets/images/logo/logo.png
  favicon: assets/images/logo/logo.png

  features:
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.select
    - content.code.annotation
    - content.code.copy

  language: en
  palette:
    - scheme: default
      primary: amber
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: amber
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - markdown.extensions.abbr:
  - markdown.extensions.admonition:
  - markdown.extensions.attr_list:
  - markdown.extensions.footnotes:
  - markdown.extensions.meta:
  - markdown.extensions.tables:
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.magiclink
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - section-index

nav:
  - index.md

  - Structural Analysis and Visualization of Networks (winter 2024 HSE):
      - courses/winter_2024_hse_savn.md

  - Courses:
      - courses/index.md
